#!/usr/bin/env python3
"""Turn a research CSV into SQL that seeds UNCLAIMED listings.

  python3 scripts/seed-unclaimed.py scripts/unclaimed-template.csv > seed.sql
Then paste seed.sql into the Supabase SQL Editor and run it.

CSV columns: company_name, hq_city, hq_country, services (slugs, ';'-separated),
lanes ('Origin>Destination' pairs, ';'-separated), website, phone.
Service slugs must match the services table (e.g. ocean-fcl, air-freight,
roro, customs-brokerage — see migration 001 for the full list).
Rules: public business information only; no ratings, no reviews, no personal data.
"""
import csv, re, sys, unicodedata

def slugify(name: str) -> str:
    s = unicodedata.normalize("NFKD", name).encode("ascii", "ignore").decode()
    s = re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")
    return s or "listing"

def esc(s: str) -> str:
    return (s or "").replace("'", "''").strip()

rows = list(csv.DictReader(open(sys.argv[1], encoding="utf-8-sig")))
print("-- Seeded unclaimed listings — generated by scripts/seed-unclaimed.py")
print("-- Safe to re-run: existing slugs are skipped.\nbegin;")
for r in rows:
    name = esc(r["company_name"])
    if not name or name.lower().startswith(("example", "sample")):
        continue  # skip the template's example rows
    slug = slugify(r["company_name"])
    city = esc(r.get("hq_city", "")); country = esc(r.get("hq_country", "Kenya"))
    website = esc(r.get("website", "")); phone = esc(r.get("phone", ""))
    print(f"""
insert into forwarder_companies
  (company_name, slug, hq_city, hq_country, website, phone,
   is_published, is_claimed, owner_id)
values ('{name}', '{slug}', {f"'{city}'" if city else "null"}, '{country}',
        {f"'{website}'" if website else "null"}, {f"'{phone}'" if phone else "null"},
        true, false, null)
on conflict (slug) do nothing;""")
    for svc in filter(None, (s.strip() for s in (r.get("services") or "").split(";"))):
        print(f"""insert into forwarder_services (forwarder_id, service_id)
select fc.id, s.id from forwarder_companies fc, services s
where fc.slug = '{slug}' and s.slug = '{esc(svc)}'
on conflict do nothing;""")
    for lane in filter(None, (l.strip() for l in (r.get("lanes") or "").split(";"))):
        if ">" not in lane: continue
        o, d = (esc(p) for p in lane.split(">", 1))
        print(f"""insert into forwarder_lanes (forwarder_id, origin_country, destination_country, modes)
select id, '{o.strip()}', '{d.strip()}', '{{}}'::freight_mode[]
from forwarder_companies where slug = '{slug}'
and not exists (select 1 from forwarder_lanes fl where fl.forwarder_id = forwarder_companies.id
                and fl.origin_country = '{o.strip()}' and fl.destination_country = '{d.strip()}');""")
print("commit;")
print(f"-- {sum(1 for r in rows if not r['company_name'].lower().startswith(('example','sample')))} listings generated", file=sys.stderr)
